all:
  children:
    demo:
      hosts:
        192.168.122.116:
          ansible_connection: ssh
          ansible_ssh_user: demo
          ansible_ssh_pass: abcdef
          #ansible_ssh_private_key_file: ./id_rsa
          ansible_sudo_pass: abcdef
